var local = {
  s1_p1: {
    it:
      "In molte regioni europee la cultura artigianale ha una lunga tradizione. Per poter salvaguardare il patrimonio culturale e artistico italiano e greco, è necessario tutelare le professioni legate alla cultura e all'artigianato tradizionale e incentivare lo sviluppo futuro delle industrie culturali e creative. Gli antichi mestieri si sono tramandati di generazione in generazione, più sotto forma di hobby creativi che di attività imprenditoriale. Questo è il background del progetto CRAFT LAB, che ha fornito l'opportunità a 60 giovani artisti / artigiani / designer (30 dalla Grecia e 30 dall'Italia) di coniugare competenze tradizionali e innovative con capacità imprenditoriali, per acquisire gli strumenti per migliorare professionalmente e , di conseguenza, diventare un esempio per i propri colleghi. A seguito di una selezione pubblica in quelle diverse aree, aperta a studenti e artisti di età compresa tra i 18 ei 35 anni, sono stati allestiti 6 laboratori per fornire esperienza: 3 in Italia (a Grottaglie per la ceramica; a Martina Franca per i tessuti; a Gravina in Puglia per i mosaici) e 3 in Grecia (a Corfù per la ceramica; a Lefkada per i tessuti; a Cefalonia per i mosaici), creando così un mix sinergico di arti e mestieri con l'obiettivo di rivitalizzare il settore artigianale attraverso l'introduzione di nuove tecnologie, e promuovere l'imprenditorialità tra i giovani e generare opportunità di lavoro nel settore. I workshop sono stati organizzati in modo da rendere disponibili i materiali e le attrezzature specifiche necessarie per realizzare prodotti di design. Della durata di quattro settimane, di cui due weekend di scambio con le controparti greche, i laboratori si sono conclusi il 30 novembre 2019 con tutti gli artisti coinvolti nel progetto che hanno esposto le proprie opere in una mostra dedicata presso la Fondazione Pino Pascali di Polignano a Mare (Bari). Il passo successivo fondamentale per la creazione di un'impresa artigianale, dopo uno studio di fattibilità, un piano di marketing e un business plan per la costituzione di una PMI, è stato realizzato dalla CNA Bari (Confederazione Nazionale Artigianato e Piccole e Medie Imprese Associazione di Bari), e l'Unione Regionale dei",
    en: `In many European regions artisanal culture has a long tradition. In order to be able to safeguard both Italian and Greek cultural and artistic heritage, it is necessary to protect the professions connected to culture and traditional craft and to incentivise the future development of the cultural and creative industries.  The ancient trades have been passed down from generation to generation, more in the shape of creative hobbies than entrepreneurial activities. This is the background to the CRAFT LAB project, which has provided the opportunity to 60 young artists/artisans/designers (30 from Greece and 30 from Italy) to combine traditional and innovative skills with entrepreneurial abilities, to acquire the tools to improve professionally and, as a consequence, to become an example for their own colleagues.  Following a public selection process in those various areas, open to students and artists aged between 18 and 35 years old, 6 laboratories were set up to provide experience: 3 in Italy (in Grottaglie for ceramics; in Martina Franca for fabrics; in Gravina in Puglia for mosaics) and 3 in Greece (in Corfù for ceramics; in Lefkada for fabrics; in Kefalonia for mosaics), thus creating a synergic mix of arts and trades with the aim of revitalising the artisanal sector through the introduction of new technologies, and promoting entrepreneurship among the young as well as generating employment opportunities in the sector. The workshops were organised in such a way as to make available the specific materials and equipment needed to create designer products. Lasting four weeks, including two exchange weekends with the Greek counterparts, the workshops ended on 30 November 2019 with all the artists involved in the project exhibiting their works in a dedicated exhibition at the Pino Pascali Foundation in Polignano a Mare (Bari). The next essential step for the creation of an artisanal business, after a feasibility study, a marketing plan and a business plan for the establishment of an SME, was carried out by the CNA Bari (National Confederation of Crafts and Small and Medium-sized Enterprises Association of Bari), and the Regional Union of`,
    gr: `Σε πολλές ευρωπαϊκές περιοχές, ο βιοτεχνικός πολιτισμός έχει μακρά παράδοση. Για να μπορέσουμε να προστατέψουμε την ιταλική και την ελληνική πολιτιστική και καλλιτεχνική κληρονομιά, είναι απαραίτητο να προστατέψουμε τα επαγγέλματα που συνδέονται με τον πολιτισμό και την παραδοσιακή τέχνη και να ενθαρρύνουμε τη μελλοντική ανάπτυξη των πολιτιστικών και δημιουργικών βιομηχανιών. Τα αρχαία επαγγέλματα μεταβιβάστηκαν από γενιά σε γενιά, περισσότερο με τη μορφή δημιουργικών χόμπι παρά με επιχειρηματικές δραστηριότητες. Αυτό είναι το υπόβαθρο του έργου CRAFT LAB, το οποίο έδωσε την ευκαιρία σε 60 νέους καλλιτέχνες / τεχνίτες / σχεδιαστές (30 από την Ελλάδα και 30 από την Ιταλία) να συνδυάσουν παραδοσιακές και καινοτόμες δεξιότητες με επιχειρηματικές ικανότητες, να αποκτήσουν τα εργαλεία για επαγγελματική βελτίωση και Κατά συνέπεια, να γίνουν παράδειγμα για τους δικούς τους συναδέλφους. Μετά από μια διαδικασία δημόσιας επιλογής σε αυτούς τους διάφορους τομείς, ανοιχτά σε μαθητές και καλλιτέχνες ηλικίας μεταξύ 18 και 35 ετών, δημιουργήθηκαν 6 εργαστήρια για να προσφέρουν εμπειρία: 3 στην Ιταλία (στο Grottaglie για κεραμικά, στη Martina Franca για υφάσματα, στη Gravina το Απουλία για ψηφιδωτά) και 3 στην Ελλάδα (στο Corfù για κεραμικά, στη Λευκάδα για υφάσματα, στην Κεφαλονιά για μωσαϊκά), δημιουργώντας έτσι ένα συνεργικό συνδυασμό τεχνών και συναλλαγών με σκοπό την αναζωογόνηση του βιοτεχνικού τομέα μέσω της εισαγωγής νέων τεχνολογιών, και προώθηση της επιχειρηματικότητας μεταξύ των νέων καθώς και δημιουργία ευκαιριών απασχόλησης στον τομέα. Τα εργαστήρια οργανώθηκαν με τέτοιο τρόπο ώστε να διατίθενται τα ειδικά υλικά και εξοπλισμός που απαιτούνται για τη δημιουργία προϊόντων σχεδιαστών. Διαρκεί τέσσερις εβδομάδες, συμπεριλαμβανομένων δύο Σαββατοκύριακων ανταλλαγής με Έλληνες ομολόγους, τα εργαστήρια έληξαν στις 30 Νοεμβρίου 2019 με όλους τους καλλιτέχνες που συμμετείχαν στο έργο να εκθέσουν τα έργα τους σε μια ειδική έκθεση στο Ίδρυμα Pino Pascali στο Polignano a Mare (Μπάρι). Το επόμενο ουσιαστικό βήμα για τη δημιουργία μιας βιοτεχνικής επιχείρησης, μετά από μια μελέτη σκοπιμότητας, ένα σχέδιο μάρκετινγκ και ένα επιχειρηματικό σχέδιο για την ίδρυση ΜΜΕ, πραγματοποιήθηκε από το CNA Bari (Εθνική Συνομοσπονδία Βιοτεχνιών και Μικρών και Μεσαίων Επιχειρήσεων) Ένωση Μπάρι), και η Περιφερειακή Ένωση του Μπάρι`,
  },
  s1_p2: {
    it: `I comuni delle Isole Ionie e la Camera di Lefkada, i partner del progetto, che attraverso il supporto tecnico di specialisti del settore hanno aiutato i giovani imprenditori a iniziare a sviluppare le loro idee imprenditoriali. Il risultato è stato la costituzione di 6 nuove start up, l'iniezione di capitale politico regionale nel settore artigianale e l'introduzione di misure a sostegno della sostenibilità economica e commerciale di prodotti di questo tipo - nuovi prodotti artigianali con una nuova croce condivisa. marchio di confine che può essere offerto ai turisti e che può fornire una via per nuovi mercati, rafforzando i contatti e la cooperazione tra i partner a tutti i livelli e stimolando l'integrazione tra i popoli attraverso attività, mostre comuni e apprendimento interculturale. Obiettivo principale del progetto Craft Lab è stato quello di avviare laboratori innovativi pensati per far rivivere i vecchi mestieri nel campo della lavorazione della ceramica, del mosaico e dei tessuti. Sembrerebbe che i sogni a volte si realizzino ... Il Progetto CRAFT-LAB, “Residences on the way from products to the adri-ionian design” è un progetto co-finanziato dall'Unione Europea, dai Fondi Europei di Sviluppo Regionale (FESR) e da Fondi nazionali di Grecia e Italia. La Fondazione Pino Pascali è la capofila di questo progetto in collaborazione con due partner italiani: Associazione Confederazione Nazionale Artigianato e Piccole e Medie Imprese di Bari, (CNA Bari) e Regione Puglia, Assessorato allo Sviluppo Economico, Istruzione, Formazione e Occupazione, e due partner greci l'Unione regionale dei comuni delle Isole Ionie e la Camera di Lefkada. Il progetto CRAFT-LAB, finanziato nell'ambito dell'Asse Prioritario 1 - Innovazione e Competitività, con un budget di circa 1 Milione di euro, mira a promuovere l'imprenditorialità e le opportunità di lavoro scoprendo e ripristinando le antiche arti e professioni nei settori della ceramica, del mosaico e del tessile.`,
    en: `Municipalities of Ionian Islands and the Chamber of Lefkada, the project partners, which through the technical support of specialists in the sector helped the young entrepreneurs to begin developing their entrepreneurial ideas. The result has been the establishment of 6 new start-ups, the injection of regional political capital into the artisanal sector and the introduction of measures to support the economic and commercial sustainability of products of this type - new artisanal products with a new shared cross-border brand that can be offered to tourists and that can provide a way into new markets, reinforcing contacts and cooperation between partners at all levels and stimulating integration between peoples through activities, joint exhibitions and intercultural learning. The main aim of the Craft Lab project was to launch innovative workshops designed to revive old trades in the fields of the working of ceramics, mosaics and textiles. It would appear that dreams sometimes come true... The CRAFT-LAB Project, “Residences on the way from products to the Adri-Ionian design” is a Project co-funded by European Union, European Regional Development Funds (E.R.D.F.) and by National Funds of Greece and Italy. The Pino Pascali Foundation is the lead beneficiary of this project in cooperation with two Italian partners the National Confederation of Crafts and Small and Medium-sized Enterprises Association of Bari, (CNA Bari) and Puglia Region, Department of Economic Development, Education, Training and Employment, and two Greek partners the Regional Union of Municipalities of Ionian Islands and the Chamber of Lefkada. The CRAFT-LAB project, financed under Priority Axis 1 – Innovation and Competitiveness, with a budget of about 1 Million euro, aims to promote entrepreneurship and job opportunities by discovering and restoring the ancient arts and professions in the ceramic, mosaic and textile fields.`,
    gr: `Δήμοι των Ιονίων Νήσων και το Επιμελητήριο της Λευκάδας, οι εταίροι του έργου, οι οποίοι μέσω της τεχνικής υποστήριξης ειδικών του κλάδου βοήθησαν τους νέους επιχειρηματίες να αρχίσουν να αναπτύσσουν τις επιχειρηματικές τους ιδέες. Το αποτέλεσμα ήταν η δημιουργία 6 νέων νεοσύστατων επιχειρήσεων, η εισφορά περιφερειακού πολιτικού κεφαλαίου στον βιοτεχνικό τομέα και η εισαγωγή μέτρων για την υποστήριξη της οικονομικής και εμπορικής βιωσιμότητας προϊόντων αυτού του τύπου - νέων βιοτεχνικών προϊόντων με ένα νέο κοινό κοινό συνοριακό σήμα που μπορεί να προσφερθεί στους τουρίστες και που μπορεί να προσφέρει έναν τρόπο σε νέες αγορές, ενισχύοντας τις επαφές και τη συνεργασία μεταξύ των εταίρων σε όλα τα επίπεδα και ενθαρρύνοντας την ένταξη μεταξύ των λαών μέσω δραστηριοτήτων, κοινών εκθέσεων και διαπολιτισμικής μάθησης. Ο κύριος στόχος του έργου Craft Lab ήταν να ξεκινήσει καινοτόμα εργαστήρια σχεδιασμένα για να αναζωογονήσουν παλιές συναλλαγές στους τομείς της κεραμικής, των ψηφιδωτών και των υφασμάτων. Φαίνεται ότι τα όνειρα μερικές φορές γίνονται πραγματικότητα ... Το CRAFT-LAB Project, "Residences on the way from the products to the Adri-Ionian design" είναι ένα έργο που συγχρηματοδοτείται από την Ευρωπαϊκή Ένωση, τα Ευρωπαϊκά Ταμεία Περιφερειακής Ανάπτυξης (ΕΤΠΑ) και από Εθνικά Ταμεία Ελλάδας και Ιταλίας. Το Ίδρυμα Pino Pascali είναι ο κύριος δικαιούχος αυτού του έργου σε συνεργασία με δύο Ιταλούς εταίρους, την Εθνική Συνομοσπονδία Βιοτεχνιών και Ένωση Μικρών και Μεσαίων Επιχειρήσεων Μπάρι, (CNA Bari) και Περιφέρεια Απουλίας, Τμήμα Οικονομικής Ανάπτυξης, Εκπαίδευσης, Κατάρτισης και Απασχόληση, και δύο Έλληνες εταίροι η Περιφερειακή Ένωση Δήμων Ιονίων Νήσων και το Επιμελητήριο Λευκάδας. Το έργο CRAFT-LAB, που χρηματοδοτείται από τον Άξονα Προτεραιότητας 1 - Καινοτομία και Ανταγωνιστικότητα, με προϋπολογισμό περίπου 1 εκατομμυρίου ευρώ, στοχεύει στην προώθηση της επιχειρηματικότητας και των ευκαιριών απασχόλησης ανακαλύπτοντας και αποκαθιστώντας τις αρχαίες τέχνες και επαγγέλματα στους τομείς των κεραμικών, των μωσαϊκών και των υφασμάτων.`,
  },
  s3_participants: {
    en: `small team of women with roots in Greece 
      Chalikia Martha, Athanasiou Pinelopi, Eftychia Karali, Κyriakou
      Aglaia, Theochari Sofia  Types of products (example categories):
      Bachelorette party items made using textile techniques (e.g.
      necklaces, earrings, etc); Personalized items - Business gifts such
      as calendars, mirrors, frames, keychains made using textile
      techniques; Bridal items`,
    gr: `μικρή ομάδα γυναικών με ρίζες στην Ελλάδα
      Χαλίκια Μάρθα, Αθανασίου Πηνελόπη, Ευτυχία Καράλη, Κυριάκου
      Αγλάια, Θεοχάρη Σόφια Τύποι προϊόντων (κατηγορίες παραδειγμάτων):
      Είδη πάρτι Bachelorette κατασκευασμένα με τεχνικές κλωστοϋφαντουργίας
      κολιέ, σκουλαρίκια, κ.λπ.) Εξατομικευμένα αντικείμενα - Επιχειρηματικά δώρα, όπως
      ως ημερολόγια, καθρέφτες, κουφώματα, μπρελόκ κατασκευασμένα από υφάσματα
      τεχνικές Νυφικά είδη`,
    it: `piccola squadra di donne con radici in Grecia
      Chalikia Martha, Athanasiou Pinelopi, Eftychia Karali, Κyriakou
      Aglaia, Theochari Sofia Tipi di prodotti (categorie di esempio):
      Articoli per addio al nubilato realizzati con tecniche tessili (ad es.
      collane, orecchini, ecc.); Articoli personalizzati - Regali aziendali come
      come calendari, specchi, cornici, portachiavi realizzati in tessuto
      tecniche; Articoli da sposa`,
  },
};

var translator = $("body").translate({
  lang: "en",
  t: local,
});

$(".lang span:first-child").click(() => {
  //   console.log("clicked");
  translator.lang("it");
});
$(".lang span:nth-child(2)").click(() => {
  //console.log("clicked2");
  translator.lang("en");
});
$(".lang span:nth-child(3)").click(() => {
  //console.log("clicked2");
  translator.lang("gr");
});

// translator.lang("it");
// translator.lang("en");
